# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_resource_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speudo', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('timezone', models.IntegerField()),
            ],
        ),
    ]
